//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.Metadatakatalog.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartkatalogen.
        /// </summary>
        public static string AppPageTitle {
            get {
                return ResourceManager.GetString("AppPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nøkkelord.
        /// </summary>
        public static string Facet_keyword {
            get {
                return ResourceManager.GetString("Facet_keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisens.
        /// </summary>
        public static string Facet_license {
            get {
                return ResourceManager.GetString("Facet_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samarbeid og lover.
        /// </summary>
        public static string Facet_nationalinitiative {
            get {
                return ResourceManager.GetString("Facet_nationalinitiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjon.
        /// </summary>
        public static string Facet_organization {
            get {
                return ResourceManager.GetString("Facet_organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjon.
        /// </summary>
        public static string Facet_organizationgroup {
            get {
                return ResourceManager.GetString("Facet_organizationgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk område.
        /// </summary>
        public static string Facet_place {
            get {
                return ResourceManager.GetString("Facet_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk område.
        /// </summary>
        public static string Facet_placegroups {
            get {
                return ResourceManager.GetString("Facet_placegroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Facet_theme {
            get {
                return ResourceManager.GetString("Facet_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Facet_type {
            get {
                return ResourceManager.GetString("Facet_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasett.
        /// </summary>
        public static string Facet_type_dataset {
            get {
                return ResourceManager.GetString("Facet_type_dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasettserie.
        /// </summary>
        public static string Facet_type_series {
            get {
                return ResourceManager.GetString("Facet_type_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjeneste.
        /// </summary>
        public static string Facet_type_service {
            get {
                return ResourceManager.GetString("Facet_type_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMS-lag (Tjenestelag).
        /// </summary>
        public static string Facet_type_servicelayer {
            get {
                return ResourceManager.GetString("Facet_type_servicelayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applikasjon.
        /// </summary>
        public static string Facet_type_software {
            get {
                return ResourceManager.GetString("Facet_type_software", resourceCulture);
            }
        }
    }
}
